/**
 * CPU & Heap Profile Analyzer
 * 
 * This script analyzes the .cpuprofile and .heapprofile files generated by Node.js
 * --cpu-prof and --heap-prof flags and provides human-readable insights about 
 * performance hotspots and memory allocation patterns.
 */

const fs = require('fs');
const path = require('path');

// ANSI color codes for terminal output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m'
};

/**
 * Parse and analyze a CPU profile file
 * @param {string} filePath - Path to the .cpuprofile file
 * @returns {Object} Analysis results
 */
function analyzeCPUProfile(filePath) {
  console.log(`\n${colors.bright}${colors.cyan}Analyzing: ${path.basename(filePath)}${colors.reset}\n`);
  
  // Read and parse the profile file
  const profileData = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  
  const { nodes, startTime, endTime, samples, timeDeltas } = profileData;
  
  // Calculate total execution time
  const totalTime = Number(endTime - startTime) / 1000; // Convert to microseconds
  const totalSamples = samples.length;
  
  // Build a map of node ID to node data
  const nodeMap = new Map();
  nodes.forEach(node => {
    nodeMap.set(node.id, {
      ...node,
      hitCount: node.hitCount || 0,
      totalHits: 0
    });
  });
  
  // Count total hits for each node (including samples)
  samples.forEach(sampleNodeId => {
    const node = nodeMap.get(sampleNodeId);
    if (node) {
      node.totalHits++;
    }
  });
  
  // Find the most expensive functions
  const expensiveFunctions = Array.from(nodeMap.values())
    .filter(node => node.totalHits > 0)
    .sort((a, b) => b.totalHits - a.totalHits)
    .slice(0, 15); // Top 15
  
  // Find our script file (not Node.js internals)
  const scriptFunctions = expensiveFunctions.filter(node => 
    node.callFrame.url.includes('memory_locality')
  );
  
  // Calculate percentages
  const calculatePercentage = (hits) => ((hits / totalSamples) * 100).toFixed(2);
  
  return {
    filePath,
    totalTime,
    totalSamples,
    expensiveFunctions,
    scriptFunctions,
    calculatePercentage
  };
}

/**
 * Display analysis results
 */
function displayAnalysis(analysis) {
  const { 
    filePath, 
    totalTime, 
    totalSamples, 
    expensiveFunctions, 
    scriptFunctions,
    calculatePercentage 
  } = analysis;
  
  console.log(`${colors.bright}═══════════════════════════════════════════════════════════${colors.reset}`);
  console.log(`${colors.bright}${colors.green}PROFILE SUMMARY${colors.reset}`);
  console.log(`${colors.bright}═══════════════════════════════════════════════════════════${colors.reset}\n`);
  
  console.log(`Total Execution Time: ${colors.yellow}${totalTime.toFixed(2)} ms${colors.reset}`);
  console.log(`Total Samples:        ${colors.yellow}${totalSamples.toLocaleString()}${colors.reset}`);
  console.log(`Sample Interval:      ${colors.yellow}~${(totalTime / totalSamples).toFixed(3)} ms/sample${colors.reset}\n`);
  
  // Display script-specific functions
  if (scriptFunctions.length > 0) {
    console.log(`${colors.bright}${colors.cyan}TOP HOTSPOTS IN YOUR CODE:${colors.reset}\n`);
    console.log(`${colors.bright}${'Function'.padEnd(50)} ${'Samples'.padEnd(12)} ${'% of Total'}${colors.reset}`);
    console.log('─'.repeat(80));
    
    scriptFunctions.forEach((node, index) => {
      const funcName = node.callFrame.functionName || '(anonymous)';
      const url = node.callFrame.url;
      const lineNo = node.callFrame.lineNumber >= 0 ? `:${node.callFrame.lineNumber}` : '';
      const location = path.basename(url) + lineNo;
      const percentage = calculatePercentage(node.totalHits);
      const bar = '█'.repeat(Math.ceil(percentage / 2));
      
      console.log(`${(index + 1).toString().padStart(2)}. ${funcName.substring(0, 35).padEnd(36)} ${node.totalHits.toString().padEnd(12)} ${percentage.padEnd(6)}% ${colors.green}${bar}${colors.reset}`);
      console.log(`    ${colors.blue}${location}${colors.reset}`);
    });
  }
  
  // Display all top functions (including Node internals)
  console.log(`\n${colors.bright}${colors.cyan}TOP 15 FUNCTIONS (INCLUDING NODE.JS INTERNALS):${colors.reset}\n`);
  console.log(`${colors.bright}${'Function'.padEnd(45)} ${'Samples'.padEnd(10)} ${'% of Total'}${colors.reset}`);
  console.log('─'.repeat(75));
  
  expensiveFunctions.slice(0, 15).forEach((node, index) => {
    const funcName = node.callFrame.functionName || '(anonymous)';
    const percentage = calculatePercentage(node.totalHits);
    const isScript = node.callFrame.url.includes('memory_locality');
    const color = isScript ? colors.yellow : colors.reset;
    
    console.log(`${color}${(index + 1).toString().padStart(2)}. ${funcName.substring(0, 40).padEnd(41)} ${node.totalHits.toString().padEnd(10)} ${percentage.padEnd(6)}%${colors.reset}`);
  });
  
  // Calculate time spent in garbage collection
  const gcNode = expensiveFunctions.find(node => 
    node.callFrame.functionName === '(garbage collector)'
  );
  
  if (gcNode) {
    const gcPercentage = calculatePercentage(gcNode.totalHits);
    console.log(`\n${colors.bright}${colors.magenta}GARBAGE COLLECTION:${colors.reset}`);
    console.log(`Time spent in GC: ${colors.yellow}${gcPercentage}%${colors.reset} of total execution`);
    
    if (parseFloat(gcPercentage) > 10) {
      console.log(`${colors.red}⚠ Warning: High GC pressure detected!${colors.reset}`);
    }
  }
  
  // Calculate time in program vs idle
  const programNode = expensiveFunctions.find(node => 
    node.callFrame.functionName === '(program)'
  );
  const idleNode = expensiveFunctions.find(node => 
    node.callFrame.functionName === '(idle)'
  );
  
  console.log(`\n${colors.bright}${colors.cyan}EXECUTION BREAKDOWN:${colors.reset}`);
  if (programNode) {
    console.log(`Program setup: ${colors.yellow}${calculatePercentage(programNode.totalHits)}%${colors.reset}`);
  }
  if (idleNode) {
    console.log(`Idle time:     ${colors.yellow}${calculatePercentage(idleNode.totalHits)}%${colors.reset}`);
  }
  
  console.log(`\n${colors.bright}═══════════════════════════════════════════════════════════${colors.reset}\n`);
}

/**
 * Analyze heap profile file
 * @param {string} filePath - Path to the .heapprofile file
 * @returns {Object} Analysis results
 */
function analyzeHeapProfile(filePath) {
  console.log(`\n${colors.bright}${colors.cyan}Analyzing: ${path.basename(filePath)}${colors.reset}\n`);
  
  // Read and parse the profile file
  const profileData = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  
  const { head, samples } = profileData;
  
  // Calculate total allocated memory
  const totalMemory = samples.reduce((sum, sample) => sum + sample.size, 0);
  
  // Traverse the tree and collect all nodes
  const allNodes = [];
  
  function traverseTree(node, depth = 0) {
    allNodes.push({
      ...node,
      depth
    });
    
    if (node.children) {
      node.children.forEach(child => traverseTree(child, depth + 1));
    }
  }
  
  traverseTree(head);
  
  // Find nodes with significant memory allocation
  const memoryHotspots = allNodes
    .filter(node => node.selfSize > 0)
    .sort((a, b) => b.selfSize - a.selfSize)
    .slice(0, 15);
  
  // Find our script allocations
  const scriptAllocations = allNodes.filter(node => 
    node.callFrame.url.includes('memory_locality') && node.selfSize > 0
  );
  
  // Calculate percentages
  const calculatePercentage = (bytes) => ((bytes / totalMemory) * 100).toFixed(2);
  const formatBytes = (bytes) => {
    if (bytes >= 1024 * 1024 * 1024) {
      return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
    } else if (bytes >= 1024 * 1024) {
      return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
    } else if (bytes >= 1024) {
      return `${(bytes / 1024).toFixed(2)} KB`;
    }
    return `${bytes} B`;
  };
  
  return {
    filePath,
    totalMemory,
    samples,
    memoryHotspots,
    scriptAllocations,
    calculatePercentage,
    formatBytes
  };
}

/**
 * Display heap analysis results
 */
function displayHeapAnalysis(analysis) {
  const { 
    filePath, 
    totalMemory, 
    samples,
    memoryHotspots, 
    scriptAllocations,
    calculatePercentage,
    formatBytes
  } = analysis;
  
  console.log(`${colors.bright}═══════════════════════════════════════════════════════════${colors.reset}`);
  console.log(`${colors.bright}${colors.green}HEAP PROFILE SUMMARY${colors.reset}`);
  console.log(`${colors.bright}═══════════════════════════════════════════════════════════${colors.reset}\n`);
  
  console.log(`Total Memory Allocated: ${colors.yellow}${formatBytes(totalMemory)}${colors.reset}`);
  console.log(`Number of Samples:      ${colors.yellow}${samples.length.toLocaleString()}${colors.reset}\n`);
  
  // Display script-specific allocations
  if (scriptAllocations.length > 0) {
    console.log(`${colors.bright}${colors.cyan}MEMORY ALLOCATIONS IN YOUR CODE:${colors.reset}\n`);
    console.log(`${colors.bright}${'Function/Location'.padEnd(50)} ${'Size'.padEnd(15)} ${'% of Total'}${colors.reset}`);
    console.log('─'.repeat(80));
    
    scriptAllocations.forEach((node, index) => {
      const funcName = node.callFrame.functionName || '(anonymous)';
      const url = node.callFrame.url;
      const lineNo = node.callFrame.lineNumber >= 0 ? `:${node.callFrame.lineNumber}` : '';
      const location = path.basename(url) + lineNo;
      const percentage = calculatePercentage(node.selfSize);
      const bar = '█'.repeat(Math.ceil(parseFloat(percentage) / 2));
      
      console.log(`${(index + 1).toString().padStart(2)}. ${funcName.substring(0, 35).padEnd(36)} ${formatBytes(node.selfSize).padEnd(15)} ${percentage.padEnd(6)}% ${colors.green}${bar}${colors.reset}`);
      console.log(`    ${colors.blue}${location}${colors.reset}`);
    });
  }
  
  // Display all top memory allocations
  console.log(`\n${colors.bright}${colors.cyan}TOP MEMORY ALLOCATIONS (INCLUDING NODE.JS INTERNALS):${colors.reset}\n`);
  console.log(`${colors.bright}${'Function/Module'.padEnd(50)} ${'Size'.padEnd(15)} ${'% of Total'}${colors.reset}`);
  console.log('─'.repeat(80));
  
  memoryHotspots.forEach((node, index) => {
    const funcName = node.callFrame.functionName || '(anonymous)';
    const moduleName = path.basename(node.callFrame.url) || 'unknown';
    const displayName = `${funcName} [${moduleName}]`;
    const percentage = calculatePercentage(node.selfSize);
    const isScript = node.callFrame.url.includes('memory_locality');
    const color = isScript ? colors.yellow : colors.reset;
    
    console.log(`${color}${(index + 1).toString().padStart(2)}. ${displayName.substring(0, 45).padEnd(46)} ${formatBytes(node.selfSize).padEnd(15)} ${percentage.padEnd(6)}%${colors.reset}`);
  });
  
  console.log(`\n${colors.bright}═══════════════════════════════════════════════════════════${colors.reset}\n`);
}

/**
 * Compare two heap profiles
 */
function compareHeapProfiles(analysis1, analysis2) {
  console.log(`\n${colors.bright}${colors.magenta}╔═══════════════════════════════════════════════════════════╗${colors.reset}`);
  console.log(`${colors.bright}${colors.magenta}║           HEAP MEMORY COMPARISON                           ║${colors.reset}`);
  console.log(`${colors.bright}${colors.magenta}╚═══════════════════════════════════════════════════════════╝${colors.reset}\n`);
  
  const name1 = path.basename(analysis1.filePath).includes('row') ? 'Row-Major' : 'Column-Major';
  const name2 = path.basename(analysis2.filePath).includes('row') ? 'Row-Major' : 'Column-Major';
  
  console.log(`${colors.cyan}${name1}:${colors.reset}`);
  console.log(`  Total Memory: ${analysis1.formatBytes(analysis1.totalMemory)}`);
  console.log(`  Samples:      ${analysis1.samples.length.toLocaleString()}`);
  
  console.log(`\n${colors.cyan}${name2}:${colors.reset}`);
  console.log(`  Total Memory: ${analysis2.formatBytes(analysis2.totalMemory)}`);
  console.log(`  Samples:      ${analysis2.samples.length.toLocaleString()}`);
  
  const memDiff = Math.abs(analysis1.totalMemory - analysis2.totalMemory);
  const ratio = Math.max(analysis1.totalMemory, analysis2.totalMemory) / 
                Math.min(analysis1.totalMemory, analysis2.totalMemory);
  const heavier = analysis1.totalMemory > analysis2.totalMemory ? name1 : name2;
  
  console.log(`\n${colors.bright}${colors.green}VERDICT:${colors.reset}`);
  
  if (ratio > 1.05) {
    console.log(`${heavier} uses ${colors.yellow}${ratio.toFixed(2)}x more memory${colors.reset}`);
    console.log(`Memory difference: ${colors.yellow}${analysis1.formatBytes(memDiff)}${colors.reset}\n`);
  } else {
    console.log(`${colors.green}Both approaches use similar memory (within 5%)${colors.reset}\n`);
  }
}

/**
 * Compare two CPU profiles
 */
function compareProfiles(analysis1, analysis2) {
  console.log(`\n${colors.bright}${colors.magenta}╔═══════════════════════════════════════════════════════════╗${colors.reset}`);
  console.log(`${colors.bright}${colors.magenta}║              PERFORMANCE COMPARISON                        ║${colors.reset}`);
  console.log(`${colors.bright}${colors.magenta}╚═══════════════════════════════════════════════════════════╝${colors.reset}\n`);
  
  const name1 = path.basename(analysis1.filePath).includes('3152') ? 'Row-Major' : 'Column-Major';
  const name2 = path.basename(analysis2.filePath).includes('3152') ? 'Row-Major' : 'Column-Major';
  
  console.log(`${colors.cyan}${name1}:${colors.reset}`);
  console.log(`  Execution Time: ${analysis1.totalTime.toFixed(2)} ms`);
  console.log(`  Total Samples:  ${analysis1.totalSamples.toLocaleString()}`);
  
  console.log(`\n${colors.cyan}${name2}:${colors.reset}`);
  console.log(`  Execution Time: ${analysis2.totalTime.toFixed(2)} ms`);
  console.log(`  Total Samples:  ${analysis2.totalSamples.toLocaleString()}`);
  
  const timeDiff = Math.abs(analysis1.totalTime - analysis2.totalTime);
  const speedup = Math.max(analysis1.totalTime, analysis2.totalTime) / 
                  Math.min(analysis1.totalTime, analysis2.totalTime);
  const faster = analysis1.totalTime < analysis2.totalTime ? name1 : name2;
  
  console.log(`\n${colors.bright}${colors.green}VERDICT:${colors.reset}`);
  console.log(`${faster} is ${colors.yellow}${speedup.toFixed(2)}x faster${colors.reset}`);
  console.log(`Time difference: ${colors.yellow}${timeDiff.toFixed(2)} ms${colors.reset}`);
  console.log(`Performance gain: ${colors.yellow}${((speedup - 1) * 100).toFixed(2)}%${colors.reset}\n`);
}

// Main execution
function main() {
  console.log(`${colors.bright}${colors.blue}`);
  console.log('╔════════════════════════════════════════════════════════════╗');
  console.log('║      CPU & HEAP PROFILE ANALYZER FOR NODE.JS              ║');
  console.log('║         Memory Locality Performance Analysis              ║');
  console.log('╚════════════════════════════════════════════════════════════╝');
  console.log(colors.reset);
  
  // Find all profile files in the current directory
  const currentDir = __dirname;
  const files = fs.readdirSync(currentDir);
  const cpuProfileFiles = files.filter(file => file.endsWith('.cpuprofile'));
  const heapProfileFiles = files.filter(file => file.endsWith('.heapprofile'));
  
  if (cpuProfileFiles.length === 0 && heapProfileFiles.length === 0) {
    console.log(`${colors.red}No profile files found in the current directory.${colors.reset}`);
    console.log(`${colors.yellow}Run the scripts with profiling flags first:${colors.reset}`);
    console.log(`  node --cpu-prof memory_locality_row_major.js`);
    console.log(`  node --cpu-prof memory_locality_column_major.js`);
    console.log(`  node --heap-prof memory_locality_row_major.js`);
    console.log(`  node --heap-prof memory_locality_column_major.js`);
    return;
  }
  
  // Analyze CPU profiles
  if (cpuProfileFiles.length > 0) {
    console.log(`\n${colors.bright}${colors.cyan}═══════════════════════════════════════════════════════════${colors.reset}`);
    console.log(`${colors.bright}${colors.cyan}                 CPU PROFILE ANALYSIS${colors.reset}`);
    console.log(`${colors.bright}${colors.cyan}═══════════════════════════════════════════════════════════${colors.reset}`);
    
    console.log(`${colors.green}Found ${cpuProfileFiles.length} CPU profile file(s):${colors.reset}`);
    cpuProfileFiles.forEach((file, index) => {
      console.log(`  ${index + 1}. ${file}`);
    });
    
    const cpuAnalyses = cpuProfileFiles.map(file => 
      analyzeCPUProfile(path.join(currentDir, file))
    );
    
    cpuAnalyses.forEach(analysis => displayAnalysis(analysis));
    
    if (cpuAnalyses.length === 2) {
      compareProfiles(cpuAnalyses[0], cpuAnalyses[1]);
    }
  }
  
  // Analyze heap profiles
  if (heapProfileFiles.length > 0) {
    console.log(`\n${colors.bright}${colors.magenta}═══════════════════════════════════════════════════════════${colors.reset}`);
    console.log(`${colors.bright}${colors.magenta}                 HEAP PROFILE ANALYSIS${colors.reset}`);
    console.log(`${colors.bright}${colors.magenta}═══════════════════════════════════════════════════════════${colors.reset}`);
    
    console.log(`${colors.green}Found ${heapProfileFiles.length} heap profile file(s):${colors.reset}`);
    heapProfileFiles.forEach((file, index) => {
      console.log(`  ${index + 1}. ${file}`);
    });
    
    const heapAnalyses = heapProfileFiles.map(file => 
      analyzeHeapProfile(path.join(currentDir, file))
    );
    
    heapAnalyses.forEach(analysis => displayHeapAnalysis(analysis));
    
    // Find matching row-major and column-major profiles
    const rowMajorHeap = heapAnalyses.find(a => 
      path.basename(a.filePath).toLowerCase().includes('row') ||
      a.scriptAllocations.some(n => n.callFrame.url.includes('row_major'))
    );
    const colMajorHeap = heapAnalyses.find(a => 
      path.basename(a.filePath).toLowerCase().includes('col') ||
      a.scriptAllocations.some(n => n.callFrame.url.includes('column_major'))
    );
    
    if (rowMajorHeap && colMajorHeap) {
      compareHeapProfiles(rowMajorHeap, colMajorHeap);
    }
  }
  
  console.log(`${colors.bright}${colors.green}✓ Analysis complete!${colors.reset}\n`);
}

// Run the analyzer
main();
